### PR TITLE
Various Sitewide Fixes & Improvements.

### LINKED ISSUE #239: Performance issues
This can probably be done during the 1.21.4 updating process.

- [x] Version-related components aren't updating immediately in some cases, need to force a re-render when switching versions - <https://vitepress.dev/guide/ssr-compat#clientonly> potential fix?
- [x] ~~Investigate whether or not [Algolia Search](https://vitepress.dev/reference/default-theme-search#algolia-search) would be better than the current local search. Local search is becoming slow due to many locales and pages. It wasn't really designed for larger documentation. Even the official vitepress documentation (which is very large in itself) uses algolia. Can apply for an open source license (no limits) here: https://docsearch.algolia.com/apply~~ - Update: It seems #259 has improved performance for some reason, worth checking to see if the improvements have stayed steady down the road.

- [x] Try https://vitepress.dev/guide/mpa-mode, I dont have high hopes that it will work though.

### PR DESCRIPTION
**Pull request by IMB11**
Closes #239 

- [x] Fixes rendering update issues with the page version warnings/reminder component.
- [x] Decreases the wrsv.nl image caching for author avatars from 1 year to 7 days.
- [x] General documentation of the various parts that make up the whole site.
- [x] Flag emoji polyfills for locale switcher on browsers which dont render flags. (Chrome on Windows for example)

### CODE REVIEW

File: .vitepress/theme/components/VersionSwitcher.vue [hunk 1]
```diff
@@ -12,102 +13,103 @@ const props = defineProps<{
...
-          `/${version}/`
-        );
+        return currentPath.replace(`/${currentVersion.value}/`, `/${version}/`);
       }
     } else {
-      route = router.route.path.replace("/", `/${version}/`);
+      return currentPath.replace("/", `/${version}/`);
     }
   }
+}
```
Comment (its-miroma) [inline .vitepress/theme/components/VersionSwitcher.vue:93]: i think this could simply be something like:

```ts
currentPath.replace(
  currentVersion.value === props.versioningPlugin.latestVersion
    ? "/"
    : `/${currentVersion.value}/`,
  newVersion.value === props.versioningPlugin.latestVersion
    ? "/"
    : `/${newVersion.value}/`
);
```

**Review by its-miroma — CHANGES_REQUESTED** [review]

File: .vitepress/theme/components/VersionSwitcher.vue (hunk 1 above)
Comment (IMB11) [reply .vitepress/theme/components/VersionSwitcher.vue:93]: Yours doesn't handle locales

Comment (its-miroma) [reply .vitepress/theme/components/VersionSwitcher.vue:93]: How so? If you've got `/it_it/1.20.4/link/to/page`, and you replace `/1.20.4/` with `/1.21/`, you end up with `/it_it/1.21/link/to/page`, which is correct

File: .vitepress/theme/CountryFlagsPolyfill.woff2
Comment (modmuss50) [inline .vitepress/theme/CountryFlagsPolyfill.woff2:1]: Where did this file come from? Whats the license?

Comment (IMB11) [reply .vitepress/theme/CountryFlagsPolyfill.woff2:1]: CC-BY, it's generated from slicing Twemoji to only add support for flags. I will add attribution when I take a look at @its-miroma's review further.

Comment (IMB11) [reply .vitepress/theme/CountryFlagsPolyfill.woff2:1]: https://github.com/twitter/twemoji#license - Graphics license.

Comment (IMB11) [reply .vitepress/theme/CountryFlagsPolyfill.woff2:1]: Just tried it, it doesn't work when switching between versions whilst a locale is present. What we have works, I dont think it needs to be changed for the sake of changing it.

File: .vitepress/theme/components/VersionSwitcher.vue (hunk 1 above)
Comment (IMB11) [reply .vitepress/theme/components/VersionSwitcher.vue:93]: Just tried it, it doesn't work when switching between versions whilst a locale is present. What we have works, I dont think it needs to be changed for the sake of changing it.

Comment (its-miroma) [reply .vitepress/theme/components/VersionSwitcher.vue:93]: I'd forgotten the dollar signs; you may keep it as is if it is not worth changing tho

File: README.md [hunk 2]
```diff
@@ -5,3 +5,10 @@ This repository contains the source code for the Fabric Documentation website, w
 ## Contributing
 
 Please refer to the [contribution guidelines](./contributing) for more information.
+
+If you wish to contribute translations, you can do so via the [Crowdin project](https://crowdin.com/project/fabricmc).
+
+## Attribution & Credits
+
+- Thank you to all the contributors that have helped create guides for the documentation! Also a huge thank you to users who have helped translate existing guides into other languages via the [Crowdin project](https://crowdin.com/project/fabricmc).
+- `CountryFlagsPolyfill.woff2` is adapted from Twemoji Mozilla by Mozilla & X (formerly Twitter) contributors, licensed under CC-BY-4.0. Modifications include storing only the flag emoticons ("Emojis"). Original license details are available at [Twemoji Mozilla](https://github.com/mozilla/twemoji-colr/blob/master/LICENSE#license-for-the-visual-design).
```
Comment (its-miroma) [inline README.md]:
```suggestion
- Thank you to all the [contributors to the repo](https://github.com/FabricMC/fabric-docs/graphs/contributors), who are helping create guides for the documentation!
- A huge thank you to users who are translating guides to other languages via the [Crowdin project](https://crowdin.com/project/fabricmc)
- `CountryFlagsPolyfill.woff2` is adapted from "Twemoji Mozilla" by Mozilla & X (formerly Twitter) contributors, licensed under CC-BY-4.0. Modifications include storing only the flag emoticons ("Emojis"). Original license details are available at [Twemoji Mozilla](https://github.com/mozilla/twemoji-colr/blob/master/LICENSE#license-for-the-visual-design)
```

**Review by its-miroma — CHANGES_REQUESTED** [review]

**Review by its-miroma — DISMISSED** [review]

**Review by modmuss50 — DISMISSED** [review]

**Review by modmuss50 — APPROVED** [review]

**Review by its-miroma — APPROVED** [review]
