### PR TITLE
fix world render VBO not closed in example code

### LINKED ISSUE #449: 1.21.5+ world renderer VBO not closed
```java
private GpuBuffer upload(MeshData.DrawState drawParameters, VertexFormat format, MeshData builtBuffer) {
	// Calculate the size needed for the vertex buffer
	int vertexBufferSize = drawParameters.vertexCount() * format.getVertexSize();

	// Initialize or resize the vertex buffer as needed
	if (vertexBuffer == null || vertexBuffer.size() < vertexBufferSize) {
		vertexBuffer = new MappableRingBuffer(() -> ExampleMod.MOD_ID + " example render pipeline", GpuBuffer.USAGE_VERTEX | GpuBuffer.USAGE_MAP_WRITE, vertexBufferSize);
	}

	// Copy vertex data into the vertex buffer
	CommandEncoder commandEncoder = RenderSystem.getDevice().createCommandEncoder();

	try (GpuBuffer.MappedView mappedView = commandEncoder.mapBuffer(vertexBuffer.currentBuffer().slice(0, builtBuffer.vertexBuffer().remaining()), false, true)) {
		MemoryUtil.memCopy(builtBuffer.vertexBuffer(), mappedView.data());
	}

	return vertexBuffer.currentBuffer();
}
```

I think growing `vertexBuffer` should close the old one at same time.

### PR DESCRIPTION
**Pull request by MukjepScarlet**
closes #449

### CODE REVIEW

File: reference/latest/src/client/java/com/example/docs/rendering/CustomRenderPipeline.java [hunk 1]
```diff
@@ -148,6 +148,9 @@ private GpuBuffer upload(MeshData.DrawState drawParameters, VertexFormat format,
 
 		// Initialize or resize the vertex buffer as needed
 		if (vertexBuffer == null || vertexBuffer.size() < vertexBufferSize) {
+			if (vertexBuffer != null) {
+				vertexBuffer.close();
+			}
```
Comment (its-miroma) [inline reference/latest/src/client/java/com/example/docs/rendering/CustomRenderPipeline.java:153]:
```suggestion
			}

```

**Review by its-miroma — CHANGES_REQUESTED** [review]

**Review by its-miroma — APPROVED** [review]

**Review by kevinthegreat1 — APPROVED** [review]
